---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - name: Get 'hello' Job information.
    k8s_info:
      kind: Job
      name: hello
      namespace: default
    register: jobs_info
  - name: Print the structure of the jobs var.
    debug:
      var: jobs_info
  - name: Assert that the 'hello' Job ran successfully.
    assert:
      that: jobs['resources'][0]['status']['succeeded'] == 1
