---
driver:
  name: delegated
lint: |
  set -e 
  yamllint .
  ansible-lint
platforms:
  - name: molecule-test
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
