---
driver:
  name: delegated
lint: |
  set -e 
  yamllint .
  ansible-lint
platforms:
  - name: molecule-test
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  env:
    KUBECONFIG: ./kubeconfig-minikube
    K8S_AUTH_KUBECONFIG: ./kubeconfig-minikube
      #KUBECONFIG: ~/.kube/config-molecule-test
      #K8S_AUTH_KUBECONFIG: ~/.kube/config-molecule-test
